### ISSUE TITLE
Would this syntax be possible/feasible?

### ISSUE THREAD

**Issue by eonist** [eonist/FileWatcher#1]
```swift
let fileWatcher = FileWatcher("url"){ 
    ...
}
```

**Comment by paperlib** [comment]
Was kind of leaving that as "nice to have" for later... but since you make it an issue :-) thought I might just commit a small extension for this right away

**Comment by eonist** [comment]
Yeh definitely nice to have for later. Left it as an Issue. Maybe someone knew how to pull it of.

**Comment by paperlib** [comment]
not for later .. you can now use the above syntax - say I had this in my tests:
```swift
let filewatcher = FileWatcher([NSString(string: "~/Desktop").expandingTildeInPath]) { event in
  print("Something different happened here: " + event.description)
}
```
:-)))

**Comment by eonist** [comment]
Awesome. 🎉
