### ISSUE TITLE
How to build for macOS 10.12?

### ISSUE THREAD

**Issue by UksusoFF** [eonist/FileWatcher#11]
Any way to build with macOS 10.12 support?

**Comment by eonist** [comment]
I'm sure it's possible to just set the Xcode library project macOS flag to 10.12. Then make a PR for that. And we can support it. I can try it when I get home from work ✌️

**Comment by UksusoFF** [comment]
Tested with override config:
```XCODE_XCCONFIG_FILE=Carthage.xcconfig" carthage build --no-use-binaries --platform macOS```

`Carthage.xcconfig` contains:
```MACOSX_DEPLOYMENT_TARGET = 10.12;```

**Comment by alioguzhan** [comment]
This makes sense since we already specified it as `10.12` in [Podspec file](https://github.com/eonist/FileWatcher/blob/master/FileWatcher.podspec#L17).
