### ISSUE TITLE
SPM Release for 0.2.2 not tagged

### ISSUE THREAD

**Issue by billThePill** [eonist/FileWatcher#19]
Modifications seem to have been made to support SPM but the latest release (0.2.2) is not tagged as such to properly pull via Xcode. A warning is displayed in getting the latest tagged release (0.2.1) in Xcode 11.4 as it doesn't support SPM.

<img width="730" alt="image" src="https://user-images.githubusercontent.com/16886642/111876535-69cd7080-895c-11eb-8d26-b9f080cdaff9.png">

<img width="301" alt="image" src="https://user-images.githubusercontent.com/16886642/111876423-ea3fa180-895b-11eb-84b8-0d013fbc0beb.png">

**Comment by eonist** [comment]
Thanks for noticing. Feel free to make a Pull-request. If you want me to do it. Let me know. 👍

**Comment by Alkenso** [comment]
@eonist , that would be great to release 0.2.2 with SPM support 🥇

**Comment by eonist** [comment]
https://github.com/eonist/FileWatcher/releases/tag/0.2.2 ✅
