### ISSUE TITLE
Place sources into 'Sources' subfolder to avoid Xcode warnings

### ISSUE THREAD

**Issue by Alkenso** [eonist/FileWatcher#20]
Xcode has warnings when add FileWatcher with SPM.

Consider to place all sources into 'Sources' subfolder to silence them.

found 3 file(s) which are unhandled; explicitly declare them as resources or exclude from the target

/Users/.../checkouts/FileWatcher/FileWatcher_macOS/Info.plist
/Users/.../checkouts/FileWatcher/README.md
/Users/.../checkouts/FileWatcher/LICENSE

**Comment by eonist** [comment]
✅ Thanks for letting me know 💚
